# Use root/example as user/password credentials
version: '3.5'

networks: 
  net-backend:
    driver: bridge

services:

  db:
    image: mariadb:10.2
    restart: always
    #env_file: 
    #  - dev.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      TZ: ${MYSQL_TIMEZONE}
    ports:
      - "3306:3306"
    networks:
      - net-backend
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
